@echo off
setlocal ENABLEDELAYEDEXPANSION
set "PYTHONUTF8=1"
set "PYTHONIOENCODING=utf-8"
set "PYTHONLEGACYWINDOWSSTDIO="

REM =========================================
REM One-click install / run (stable)
REM Filename: run_app.bat (ASCII-only)
REM Generated by scripts\project_launcher.py
REM Project type: web_split
REM =========================================

pushd "%~dp0"
if not exist "logs" mkdir "logs" >nul 2>nul

echo =========================================
echo   One-click install / run (stable)
echo =========================================
echo.

echo [1/6] Checking Python...
where python >nul 2>&1
if errorlevel 1 (
  echo.
  echo [ERROR] Python not found. Please install Python 3.10+ first.
  echo Download: https://www.python.org/downloads/
  echo.
  pause
  popd
  exit /b 1
)

echo [2/6] Creating venv (.venv) if needed...
if not exist ".venv\Scripts\python.exe" (
  python -m venv ".venv" 1>>"logs\bootstrap.log" 2>>&1
  if errorlevel 1 (
    echo [WARN] Failed to create venv. Falling back to system Python.
  )
)

set "PYEXE=%~dp0.venv\Scripts\python.exe"
if not exist "%PYEXE%" set "PYEXE=python"

echo [3/6] Auto-fix + install dependencies...
"%PYEXE%" "scripts\project_launcher.py" --root "%CD%" --venv ".venv" --ensure-only 1>>"logs\ensure.log" 2>>&1
if errorlevel 1 (
  echo [WARN] Auto-fix or install step reported issues. See logs\ensure.log.
) else (
  echo [OK] Auto-fix and install step completed.
)



echo [4/6] Starting backend or local app...
echo Start time: %DATE% %TIME%
start "Backend" /d "%~dp0" "%~dp0scripts\launch_backend.bat"

echo [5/6] Starting frontend (Node project)...
echo [INFO] Frontend dir: apps\web
start "Frontend" /d "%~dp0" "%~dp0scripts\launch_frontend.bat"
echo [6/6] Opening browser or app URLs...
timeout /t 2 >nul
start "" "http://127.0.0.1:8000"
start "" "http://127.0.0.1:5173"


echo.
echo =========================================
echo Startup flow finished.
echo Logs directory: %CD%\logs
echo Close Backend / Frontend / GUI windows to stop services.
echo =========================================
echo.
pause
popd
endlocal
